[[plugins]]
repo = 'sickill/vim-monokai'
[[plugins]]
repo = 'nanotech/jellybeans.vim'
[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'bkad/CamelCaseMotion'
hook_add = '''
    map <silent> W <Plug>CamelCaseMotion_w
    map <silent> B <Plug>CamelCaseMotion_b
    map <silent> E <Plug>CamelCaseMotion_e
    map <silent> ge <Plug>CamelCaseMotion_ge
    sunmap W
    sunmap B
    sunmap E
    sunmap ge
    omap <silent> iW <Plug>CamelCaseMotion_iw
    xmap <silent> iW <Plug>CamelCaseMotion_iw
    omap <silent> iB <Plug>CamelCaseMotion_ib
    xmap <silent> iB <Plug>CamelCaseMotion_ib
    omap <silent> ie <Plug>CamelCaseMotion_ie
    xmap <silent> ie <Plug>CamelCaseMotion_ie
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
    nmap <Leader>s <Plug>(easymotion-s2)
    let g:EasyMotion_keys = 'hgjfkdls'
'''

# yank highlight
[[plugins]]
repo = 'machakann/vim-highlightedyank'
hook_add = '''
    let g:highlightedyank_highlight_duration = 200
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
    let g:indent_guides_enable_on_vim_startup=1
    let g:indent_guides_auto_colors=0
    autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd guibg=#444433 ctermbg=black
    autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=#333344 ctermbg=darkgray
    let g:indent_guides_guide_size = 1
'''

[[plugins]]
repo = "Shougo/denite.nvim"
hook_add = """
source ~/dotfiles/.vim/plugins/denite.rc.vim
"""

[[plugins]]
repo = "shougo/deol.nvim"
hook_add = """
source ~/dotfiles/.vim/plugins/deol.rc.vim
"""
 
[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
  if has('mac')
    nnoremap <Leader>b :NERDTreeToggle<CR>
  else
    nnoremap <A-b> :NERDTreeToggle<CR>
  endif
'''
# if you want to see dot files or folders, press "shift + i" after :NERDTreeToggle.

# icon for NERDTREE
[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
'''

# status bar
[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
    let g:tagbar_width = 30
    let g:tagbar_autoshowtag = 1
    let g:tagar_autofocus = 1
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
    " カラーテーマ指定してかっこよく
    "let g:airline_theme = 'badwolf'
    let g:airline_theme = 'tender'
    let g:airline_powerline_fonts = 1
    set laststatus=2
    " タブバーをかっこよく
    let g:airline#extensions#tabline#enabled = 1
    "let g:airline_section_c = airline#section#create(['bufferline', 'filename', 'readonly'])
    " 選択行列の表示をカスタム(デフォルトだと長くて横幅を圧迫するので最小限に)
"    let g:airline_section_z = airline#section#create(['windowswap', '%3p%% ', 'linenr', ':%3v'])
    " virtulenvを認識しているか確認用に、現在activateされているvirtualenvを表示(vim-virtualenvの拡張)
    let g:airline#extensions#virtualenv#enabled = 1
    " gitのHEADから変更した行の+-を非表示(vim-gitgutterの拡張)
    let g:airline#extensions#hunks#enabled = 0
    " Lintツールによるエラー、警告を表示(ALEの拡張)
    let g:airline#extensions#ale#enabled = 1
    let g:airline#extensions#ale#error_symbol = 'E:'
    let g:airline#extensions#ale#warning_symbol = 'W:'
'''

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'leafgarland/typescript-vim'

# quick run
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
'''

