#[[plugins]]
#repo = 'Sougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
    nmap <Leader>s <Plug>(easymotion-s2)
    let g:EasyMotion_keys = 'hgjfkdls'
'''

[[plugins]]
repo = 'Shougo/unite.vim'

# indent
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup=1
  let g:indent_guides_auto_colors = 0
  let g:indent_guides_exclude_filetypes = ['help', 'vimfiler']
'''

[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
  nnoremap <C-b> :NERDTreeToggle<CR>
'''

