[[plugins]]
repo = "puremourning/vimspector"
on_ft = ["python", "javascript"]
build = '''
    /install_gadget.py 
        --enable-python
        --force-enable-node
        --force-enable-php
'''
hook_add = '''
    let g:vimspector_base_dir = expand('$HOME/.config/vimspector-config')
    nmap <Space>db <Plug>VimspectorToggleBreakpoint
    nmap <Space>dl :call vimspector#Launch()<CR>
    nmap <Space>dq :VimspectorReset<CR>
    nmap <Space>de :VimspectorEval
    nmap <Space>dw :VimspectorWatch
    nmap <Leader>dc <Plug>VimspectorContinue
    nmap <Leader>do <Plug>VimspectorStepOver
    nmap <Leader>di <Plug>VimspectorStepInto
    nmap <Leader>drst <Plug>VimspectorRestart

'''

