[[plugins]]
repo = 'sickill/vim-monokai'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
    nmap <Leader>s <Plug>(easymotion-s2)
    let g:EasyMotion_keys = 'hgjfkdls'
'''

[[plugins]]
repo = 'Shougo/unite.vim'

# indent
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
    let g:indent_guides_enable_on_vim_startup=1
    let g:indent_guides_auto_colors = 1
    autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=red   ctermbg=236
                autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=green ctermbg=237
'''

[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
  if has('mac')
    nnoremap <Leader>b :NERDTreeToggle<CR>
  else
    nnoremap <A-b> :NERDTreeToggle<CR>
  endif
'''
# if you want to see dot files or folders, press "shift + i" after :NERDTreeToggle.

# status bar
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
    " カラーテーマ指定してかっこよく
    "let g:airline_theme = 'badwolf'
    let g:airline_powerline_fonts = 1
    set laststatus=2
    " タブバーをかっこよく
    let g:airline#extensions#tabline#enabled = 1
    " 選択行列の表示をカスタム(デフォルトだと長くて横幅を圧迫するので最小限に)
    let g:airline_section_z = airline#section#create(['windowswap', '%3p%% ', 'linenr', ':%3v'])
    " virtulenvを認識しているか確認用に、現在activateされているvirtualenvを表示(vim-virtualenvの拡張)
    let g:airline#extensions#virtualenv#enabled = 1
    " gitのHEADから変更した行の+-を非表示(vim-gitgutterの拡張)
    let g:airline#extensions#hunks#enabled = 0
    " Lintツールによるエラー、警告を表示(ALEの拡張)
    let g:airline#extensions#ale#enabled = 1
    let g:airline#extensions#ale#error_symbol = 'E:'
    let g:airline#extensions#ale#warning_symbol = 'W:'
'''

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

