
# vim suggestion
[[plugins]]
repo = 'Shougo/neco-vim'

# language server plotocol
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'realease'
on_i = 1
merged = '0'
hook_source = 'call call398#init#coc#hook_source()'
